### ISSUE TITLE
Enhancement Request: breakdown temp and cpufreq by big.little

### ISSUE THREAD

**Issue by bigLITTLEData** [avafinger/htop-2.1.1_enhanced-version#1]
First off, thanks so much for implementing this, extremely useful to monitor the hardware.

I'm running it on a Nanopc T4, also RK3399, and this works great.

I've got a request for an enhancement.

You already break down the CpuVcore by big.LITTLE:

Cpu Vcor: 800 mv, 1.12 V  (big.LITTLE)

On the RK3399, there are really only two temps and two cpufreqs (similar to Vcore above):

pi@NanoPC-T4:~$ ls -l /sys/devices/system/cpu/cpufreq/policy?/cpuinfo_cur_freq /sys/class/thermal/thermal_zone?/temp
-r--r--r-- 1 root root 4096 Dec 24 00:39 /sys/class/thermal/thermal_zone0/temp
-r--r--r-- 1 root root 4096 Dec 24 00:39 /sys/class/thermal/thermal_zone1/temp
-r-------- 1 root root 4096 Dec 24 00:39 /sys/devices/system/cpu/cpufreq/policy0/cpuinfo_cur_freq
-r-------- 1 root root 4096 Dec 24 00:39 /sys/devices/system/cpu/cpufreq/policy4/cpuinfo_cur_freq

The zone0/policy0 applies to the LITTLE cores.  This one temp and cpufreq applies to all LITTLE cores (the LITTLE cluster as a whole).

And similarly, zone1/policy4 apply to the big cores.  Again, this one temp and cpufreq applies to all the big cores (the big cluster).

Here is what I get on my machine:

pi@NanoPC-T4:~$ sudo cat /sys/devices/system/cpu/cpufreq/policy?/cpuinfo_cur_freq /sys/class/thermal/thermal_zone?/temp
1416000
816000
31111
30555

Could you change the CpuTemp to look like this:

Cpu Temp:    30 C   31 C  (big.LITTLE)

Or maybe just add a separate big and LITTLE variant of CpuTemp:

Cpu Temp:                31 C  (   .LITTLE)
Cpu Temp:    30 C              (big.      )

Similarly, for CpuFreq:

Cpu Freq: .82 GHz 1.42 GHz (big.LITTLE)

Or break it into two CpuTemp's, one for LITTLE and another for big.

I've seen cases where LITTLE temp is > 40 while big temp is in the 30's.

Would be nice to see both cluster's temps and freq separately.  Pretty much eliminates the need for CpuFreq 1 through 6.

Thanks, keep up the good work!

**Comment by avafinger** [comment]
Thanks for pointing it out.
I will try to add it in this way: Cpu Temp: 30 C 31 C (big.LITTLE).

Which kernel version are you using? Seems to be the mainline kernel !?!

ops.. sorry i was in the wrong board.

Edit:
```
ls /sys/devices/system/cpu/cpufreq/policy?
/sys/devices/system/cpu/cpufreq/policy0:
affected_cpus		    related_cpus		   scaling_max_freq
cpuinfo_cur_freq	    scaling_available_frequencies  scaling_min_freq
cpuinfo_max_freq	    scaling_available_governors    scaling_setspeed
cpuinfo_min_freq	    scaling_cur_freq		   stats
cpuinfo_transition_latency  scaling_driver
interactive		    scaling_governor

/sys/devices/system/cpu/cpufreq/policy4:
affected_cpus		    related_cpus		   scaling_max_freq
cpuinfo_cur_freq	    scaling_available_frequencies  scaling_min_freq
cpuinfo_max_freq	    scaling_available_governors    scaling_setspeed
cpuinfo_min_freq	    scaling_cur_freq		   stats
cpuinfo_transition_latency  scaling_driver
interactive		    scaling_governor

```
and:

`sudo cat /sys/devices/system/cpu/cpufreq/policy?/cpuinfo_cur_freq /sys/class/thermal/thermal_zone?/temp`
1008000
408000
32777
32222

**Comment by bigLITTLEData** [comment]
I've had the Nanopc T4 for a new months now, but I just downloaded the
latest distribution from friendlyelec's download site:


rk3399-sd-friendlydesktop-bionic-4.4-arm64-20181219.img.zip


Here is the kernel:

pi@NanoPC-T4:~$ uname -a
Linux NanoPC-T4 4.4.143 #1 SMP Tue Nov 20 11:10:11 CST 2018 aarch64 aarch64
aarch64 GNU/Linux

I'm running with their stock kernel.

I see the same things you do, the above path works for me as well.

There are a bunch of *symlinks,* so the temps show up on two different
paths.  Either your path or mine should work, take your pick.

root@NanoPC-T4:*/sys/class/thermal*# ls -ld therm*
thermal_zone0 -> ../../devices/virtual/thermal/thermal_zone0
thermal_zone1 -> ../../devices/virtual/thermal/thermal_zone1

The /sys/class/thermal/thermai_zone* directories are just symlinks off to
the real directory under that /sys/devices/virtual/thermal directory.

So, both of these paths point to the same directory:

/sys/class/thermal/thermal_zone0
/sys/devices/virtual/thermal/thermal_zone0

Use whichever you prefer.

Thanks.

I'm running your temp/freq/vcore enhanced htop constantly on my Nanopc
T4 now, works great.

I noticed you've got one for the H5 chip as well.  I have a several
Nanopi Neo2's, I'll have to try your enhanced htop for that as well.
That one is much simpler, with just one cluster of 4 cores, probably
just one cpufreq, vcore and temp.

Thanks for all the good work, I really appreciate it!

Have a Merry Xmas.

 - Mark

**Comment by avafinger** [comment]
@bigLITTLEData 
Thank you. The same to you.

Pushing the changes to github. Please try this and see if works.
![2018-12-25-191850_579x387_scrot](https://user-images.githubusercontent.com/16623039/50426649-b360ab00-087a-11e9-8e13-2343e0611a62.png)

**Comment by avafinger** [comment]
Please, check out branch: rk3399

**Comment by bigLITTLEData** [comment]
Looks good, but I goofed on the thermals for the rk3399 board, sorry I
missed this, I should have checked this earlier.

The thermal_zone0 is the CPU (System On a Chip) temp:

root@NanoPC-T4:*/sys/devices/virtual/thermal/thermal_zone0*# cat type
soc-thermal

The thermal_zone1 is the GPU (Graphics Processing Unit) temp:

root@NanoPC-T4:*/sys/devices/virtual/thermal/thermal_zone1*# cat type
gpu-thermal

Which is interesting in itself.  You might consider adding an additional
htop item for GPU Temp!

I'd just change the CPU Temp back to a single number based on thermal_zone0
as before.

Sorry for pointing you in the wrong direction.  The CPU Freq looks great
though!

I'm certain about the CPU only having big and LITTLE frequency, check out
the /sys tree on this:

root@NanoPC-T4:*/sys/devices/system/cpu*# ls -l cpu*/cpufreq
lrwxrwxrwx 1 root root 0 Dec 26 00:29 cpu0/cpufreq -> ../cpufreq/policy0
lrwxrwxrwx 1 root root 0 Dec 25 23:21 cpu1/cpufreq -> ../cpufreq/policy0
lrwxrwxrwx 1 root root 0 Dec 25 23:21 cpu2/cpufreq -> ../cpufreq/policy0
lrwxrwxrwx 1 root root 0 Dec 25 23:21 cpu3/cpufreq -> ../cpufreq/policy0
lrwxrwxrwx 1 root root 0 Dec 26 00:29 cpu4/cpufreq -> ../cpufreq/policy4
lrwxrwxrwx 1 root root 0 Dec 25 23:21 cpu5/cpufreq -> ../cpufreq/policy4

As you can see, the 4 LITTLE CPUs all point to the policy0 which is where
you pick up the CPU frequency by core.  And the 2 big CPUs both point to
the policy4.  I believe CPU freq is fine.

Really cleans up the display, here is what I see:

Cpu Vcor: 800 mV 1.12 V (big.LITTLE)
Cpu Freq: 408 MHz 1.42 GHz (big.LITTLE)

Very nice!  The tuning that Friendly Elec seems to do runs the LITTLE cores
as maximum freq all the time (1.42 GHz) while keeping the big cores at the
minimum (408 MHz) until stressed, then it jumps to the max of 1.8 Ghz

You might consider keeping the individual CPU Freq 1 through 6 that you had
previously, if anyone else liked that detailed display.

Thanks again.

 - Mark

**Comment by avafinger** [comment]
Interesting, my kernel stress first the big cluster and then the LITTLE cluster.

`cat /sys/devices/system/cpu/cpufreq/policy0/scaling_governor /sys/devices/system/cpu/cpufreq/policy4/scaling_governor
`
**interactive
interactive**

Pushing the changes to github:
![2018-12-26-103321_579x387_scrot](https://user-images.githubusercontent.com/16623039/50446074-075ea480-08fa-11e9-8763-c82a5cd067b7.png)

![2018-12-26-103512_579x387_scrot](https://user-images.githubusercontent.com/16623039/50446084-147b9380-08fa-11e9-922d-30abfce24381.png)

**Comment by bigLITTLEData** [comment]
Oh, interesting.  My scaling_governors are set to performance/interactive
(LITTLE/big).  No wonder.

Your new upload looks great.  Thanks for all the hard work, and fixing my
misdirection.  We got GPU Temp out of it though which is cool.

So that performance/interactive seems to run the LITTLE cores at full tilt
all the time (wasting power by the way) trying to provide enough LITTLE
low-power cores to run all available work, and when they saturate, only
then spins up the big cores.

By the way, you can change those if you are under root/sudo:

echo interactive > scaling_governor

The Friendlyelec kernal (at least) has these available options:

   - conservative
   - ondemand
   - userspace, but you need to set scaling speed (not sure it's supported):
   -       echo 600000 >
   /sys/devices/system/cpu/cpu0/cpufreq/scaling_setspeed
   - powersave
   - interactive
   - performance

I note that powersave always seems to run at minimum freq (laptop with low
battery I guess).  And performance always runs at the max frequency.

Thanks again, I'll check out your H5 htop stuff.

 - Mark

**Comment by avafinger** [comment]
The missing files and minor fix now update, it is now possible to build from source. There is a branch for mainline kernel if you would like to run mainline 5.x on your board. If there is any other issue, please reopen.
